version: '3'
services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  strapi:
    image: ethienneroy/evoketennis:v1.0.0
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data.db
    volumes:
      - ./app:/srv/app
    ports:
      - 1337:1337
  nextjs:
    build: ./app
    ports:
      - 3000:3000
    depends_on:
      - strapi

